<?php

/**
 * Implements hook_mail().
 */
function call_login_mail($key, &$message, $params)
{
    $options = array(
        'langcode' => $message['langcode'],
    );

    switch ($key) {
        case 'small_balance':
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = 'Низкий баланс! SMS.RU';
            $message['body'][] = $params['message'];
            break;

        case 'login_error':
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = 'Ошибка входа - SMS.RU';
            $message['body'][] = $params['message'];
            break;
    }
}
